### ISSUE TITLE
SELinux in Kernel

### ISSUE THREAD

**Issue by ruchernchong** [sktjdgns1189/android_kernel_samsung_kccat6#2]
Does this kernel allow toggling of SELinux between Enforcing and Permissive?

If no, where can I edit this kernel and build it for my own use?

Thanks!

**Comment by sktjdgns1189** [comment]
Reverting this commit https://github.com/sktjdgns1189/android_kernel_samsung_kccat6/commit/599ea327d1276fb0fa4824c3c20ebe1ca4dbd71a
You can set SELinux to Enforcing.
